---
title: "Data Frame"
output: html_document
---


## Data Frame Bicimlendirme


```{r}


df <- data.frame(
  
  magaza_no = c(1:5),
  semt = c("Mecidiyekoy", "Levent", "Sarikoy", "Gop", "Kagithane"),
  ortolama_kazanc = c(60,50,61,72,89),
  stringsAsFactors = FALSE  #  Karakter degiskeni factor deisken olmasini engeller
)


str(df)   # veri seti hakkinda bilgi veren bir fonksiyon genel bir yapi

summary(df)   # veri seti hakkinda özet bilgi veren bir fonksiyon genel bir yapi


dim(df)   # boyutunu verir


df2 <- data.frame(
  
  magaza_no = c(1:5),
  gecmis = c(2,4,5,2,3),
  personel_sayisi = c(60,50,61,72,89)
)


merge(df, df2)


merge(df, df2, by = "magaza_no")


cbind(df, df2)

rbind(df, df)  # 2 farklı dataframe birlestirmek icin row isimlerinin ayni olmasi lazim


```



## Data Frame Gozlem ve Degisken ekle cikar


```{r df_all}


df_all <- merge(df, df2, by = "magaza_no")

df_all

df_all$ort_mus <- c(1,3,5,7,9)  # degisken eklenmis olur

df_all$bos <- c(1,3,5,7,9)

df_all$bos <- NULL  # degsikeni siler


df_all$per_bas_kaz <- df_all$ortolama_kazanc / df_all$personel_sayisi


rbind(df_all, c(6, "Beyoglu", 99, 6, 12, 34, 1))   # satir eklenir


df_all[-6]  # 6. satırı siler


```



## Data Frame isimlendirme


```{r echo=FALSE}

colnames(df) <- c("n", "r", "s")

rownames(df) <- c("1","2","3","4","5")

df$r <- tolower(df$r)

df


# semt degiskenlerini satır ismi olarak atama yapılıyor

df_all

library(dplyr)
library(tibble)

df_all %>% remove_rownames %>% column_to_rownames(var = "semt")


```



## Liste veya Matrixleri Data Frame Donusturme


```{r include=FALSE}

m <- matrix(1:9, 3, 3)

df <- as.data.frame(m)

df

sayi <- c(1,2,3)
harf <- c("a", "b", "c")
log <- c(TRUE, FALSE, TRUE)

liste <- list(sayi, harf, log)

df <- as.data.frame(liste)


```



## Data Frame Eleman islemleri


```{r }


library(ggplot2)

mpg


summary(mpg)

str(mpg)

mpg$manufacturer

mpg$model


#mpg nin degikenleriyle yeni bir vei seti olusturulabilir

#head fonksiyonu ilk kaç staırı göstericegini belirtir

head(data.frame(mpg$manufacturer, mpg$model), 10)

degiskenler <- c("model", "year", "cyl")

data <- mpg[degiskenler]

# belirli durumlardaki degsikenleri alma islemi

mpg[mpg$manufacturer == "Audi" & mpg$cyl == "6" & mpg$year > 1999, ]

mpg

```



## Data Frame Siralama


```{r }

df_all

#semt isimlerine gore siralama

df_all[order(df_all$semt, decreasing = TRUE),]

```





## Aplly Fonsksiyonlari



```{r }

##########    microbenchmark fonksiyonu iki fonksiyonu arasında performans karsilastirmasi yapar
##########    source fonksiyonu başka dosyalardaki kodlara ulasmayi saglar


# lapply  listelerin islemlerinin sonucunu liste olarak donurur


l <- list( a = rnorm(90),
      b = rbeta(10,1,2),
      c = 1:5000
      )

lapply(l, mean)




# sapply  listelerin degerlerini vectore donusturur


l <- list( a = rnorm(90),
      b = rbeta(10,1,2),
      c = 1:5000
      )

sapply(l, mean)


# vapply ciktinin tipini garanti altina alir

vapply(1:10, sqrt, double(1))


# tapply dataframe icerisndeki kategorik degiskenlerin kiriliiminda fonksiyonlari calismasini saglar

str(mpg)

tapply(mpg$cyl, mpg$class, mean)


by(mpg[, c("displ", "cty", "hwy")], mpg$cyl,  colMeans)


```





## Map Fonsksiyonlari



```{r }

library(purrr)

mapp <- mpg[, c("displ", "cty", "hwy")]

map_dbl(mapp, mean)

mtcars %>% split(.$cyl) %>% map(~ lm(mpg ~ wt, data = .)) %>% map(summary) %>% map_dbl("r.squared") 


```


## Tibble 



```{r }

# data frame in modern anlamda yeniden tasarlanmis hali

# yazdırmada oluşturulan tibble in az elemanini gosterir  dataframe hepsini gosterir


tibble(
  a = 1:10000,
  b = 1:10000
)

#bir veri setini tibble a donusturur

as_tibble(iris)  

```





